### ISSUE TITLE
Image Upside Down

### ISSUE THREAD

**Issue by seagal112** [shauninman/union-miyoomini-toolchain#1]
Hi! Everything that i try to compile is showed upside down. Is a toolchain problem or I'm doing anything wrong? 

Example (Ohboy Gameboy emulator):

https://www.amazon.es/photos/share/zuSJJ8KmRYr8eiLXMwY4igKZbol9hYnmHqFfvdVq9wp

**Comment by shauninman** [comment]
Not sure why I wasn’t notified about this. It is not a toolchain problem. The Mini’s screen is installed upside down and the stock libs only rotate correctly if a certain set of conditions are met. I’ve forgotten what those exact conditions are since I created a custom SDL that automatically handles rotation.
